In [1]:
#import packages
import pandas as pd
import numpy as np
import yfinance as yf

pd.options.display.float_format = '{:,.0f}'.format

In [ ]:
#Download DATA
ticker = yf.Ticker("AAPL")

df = yf.download(tickers= "AAPL", start= "2025-01-01", end="2025-12-31", group_by= "columns")
stockprice = df["AAPL"]["Close"]["2025-09-30"]

#Balance Sheet
bs = ticker.balance_sheet

#Income Statement
income_stmt = ticker.income_stmt

#CashFlow
cashflow = ticker.cashflow

[*********************100%***********************]  1 of 1 completed

In [12]:
##Simple Plan Model
#Simple Income Statement
sales = income_stmt.loc["Total Revenue"]
costs = income_stmt.loc['Total Expenses']
net_income = sales - costs

simple_income_stmt = pd.DataFrame({
    "sales":sales,
    "costs" : costs,
    "net_income" : net_income
}, index = ["2025-09-30"])

simple_income_stmt.T

                2025-09-30
sales      416,161,000,000
costs      283,111,000,000
net_income 133,050,000,000

In [38]:
#Simple Balance Sheet
simple_total_assets = bs.loc["Total Assets"]
simple_total_debt = bs.loc["Total Liabilities Net Minority Interest"]
simple_total_equity = bs.loc["Stockholders Equity"]

simple_balance_sheet = pd.DataFrame({
    "asset" : simple_total_assets,
    "debt" : simple_total_debt,
    "equity" : simple_total_equity
}, index=["2025-09-30"])

simple_balance_sheet.T

            2025-09-30
asset  359,241,000,000
debt   285,508,000,000
equity  73,733,000,000

In [ ]:
#Make Target income statement, the aim is 20%
aim = 0.2

future_sales = sales["2025-09-30"] * (1+aim)
future_costs = costs["2025-09-30"] * (1+aim)
future_net_income = future_sales - future_costs

future_income_stmt = pd.DataFrame({
    "sales": future_sales,
    "costs" : future_costs,
    "net_income" : future_net_income
}, index = ["future"])


income_stmt_result = pd.concat([simple_income_stmt, future_income_stmt])

np.float64(26610000000.0)

In [40]:
#Make Target Balance Sheet, the aim is 20%

future_total_asset = simple_total_assets["2025-09-30"] * (1+aim)
future_total_debt = simple_total_debt["2025-09-30"] * (1+aim)
future_total_equity = simple_total_equity["2025-09-30"] * (1+aim)

future_balance_sheet = pd.DataFrame({
    "asset" : future_total_asset,
    "debt" : future_total_debt,
    "equity" : future_total_equity
}, index = ["future"])

balance_sheet_result = pd.concat([simple_balance_sheet, future_balance_sheet])
balance_sheet_result.T

            2025-09-30          future
asset  359,241,000,000 431,089,200,000
debt   285,508,000,000 342,609,600,000
equity  73,733,000,000  88,479,600,000

                 asset            debt         equity
future 431,089,200,000 342,609,600,000 88,479,600,000