In [1]:
#import packages
import pandas as pd
import numpy as np

In [25]:
#protevtive put
investing = 115
s0 = 110
e = 105
t = 1
option_premium = 5

s1 = np.arange(125,89,-5)
c1 = []
for i in range(len(s1)):
    if s1[i] - e >= 0:
        c1.append(0)
    else:
        c1.append(e-s1[i])

total_value = s1+c1
earn = total_value-115

result = pd.DataFrame({
    "s1": s1,
    "c1": c1,
    "total_value": total_value,
    "earn":earn
})

result

    s1  c1  total_value  earn
0  125   0          125    10
1  120   0          120     5
2  115   0          115     0
3  110   0          110    -5
4  105   0          105   -10
5  100   5          105   -10
6   95  10          105   -10
7   90  15          105   -10

In [ ]:
#alternative strategy, using call option & risk free asset
investing = 115
s0 = 110
e = 105
t = 1
option_premium = 15
rf = 0.05
rf_invest = 100


s1 = np.arange(125,89,-5)
c1 = []
rf_value = []
for i in range(len(s1)):
    if s1[i] - e <= 0:
        c1.append(0)
        rf_value.append(int(rf_invest*(1+rf)))
    else:
        c1.append(s1[i]-e)
        rf_value.append(int(rf_invest*(1+rf)))

total_value = np.array(c1) + np.array(rf_value)

earn = total_value-115

result = pd.DataFrame({
    "s1": s1,
    "c1": c1,
    "rf_value" : rf_value,
    "total_value": total_value,
    "earn":earn
})

result
#At result, it is same. Put Call Parity(PCP)
# 1 Stock + Put Option = C0 + Call option
# S + P = PV(E) + C
# S = PV(E) + C - P

    s1  c1  rf_value  total_value  earn
0  125  20       105          125    10
1  120  15       105          120     5
2  115  10       105          115     0
3  110   5       105          110    -5
4  105   0       105          105   -10
5  100   0       105          105   -10
6   95   0       105          105   -10
7   90   0       105          105   -10